version: '3'

services:
  db:
    image: postgres
    # volumes:
      # -postgres_data:var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    # volumes:
      # -postgres_data:var/lib/postgresql/data/

  redis:
    image: redis

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - redis
    # links:
      # - redis

  worker:
    build: .
    command: celery -A CryptoPriceChecker worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    links:
      - redis

  beat:
    build: .
    command: celery -A CryptoPriceChecker beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    links:
      - redis

  # volumes:
    # postgres_data: